// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.8.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<(int, int)>> getInputRegisters({dynamic hint}) =>
    RustLib.instance.api.getInputRegisters(hint: hint);

Future<void> serverContext(
        {required String socketAddr, required Notify notify, dynamic hint}) =>
    RustLib.instance.api
        .serverContext(socketAddr: socketAddr, notify: notify, hint: hint);

// Rust type: flutter_rust_bridge::RustOpaque<std::sync::RwLock<std :: sync :: Arc < tokio :: sync :: Notify >>>
@sealed
class Notify extends RustOpaque {
  Notify.dcoDecode(dynamic wire) : super.dcoDecode(wire, _kStaticData);

  Notify.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Notify,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Notify,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NotifyPtr,
  );
}
