// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.8.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'modbus_server.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Notify> getNotify({dynamic hint}) =>
    RustLib.instance.api.getNotify(hint: hint);

void stopServer({dynamic hint}) => RustLib.instance.api.stopServer(hint: hint);
